In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(np.arange(0, 15).reshape(5, 3), columns=['a', 'b', 'c'])
df

    a   b   c
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

In [3]:
df['d'] = np.nan
df['e'] = np.arange(15, 20)
df.loc[5,:] = pd.NA
df.loc[4,'a'] = pd.NA
df.loc[0,'d'] = 1
df.loc[5,'d'] = 10
df

      a     b     c    d     e
0     0     1     2    1    15
1     3     4     5  NaN    16
2     6     7     8  NaN    17
3     9    10    11  NaN    18
4  <NA>    13    14  NaN    19
5  <NA>  <NA>  <NA>   10  <NA>

In [4]:
df.isnull()

       a      b      c      d      e
0  False  False  False  False  False
1  False  False  False   True  False
2  False  False  False   True  False
3  False  False  False   True  False
4   True  False  False   True  False
5   True   True   True  False   True

In [5]:
df.isnull().sum()

a    2
b    1
c    1
d    4
e    1
dtype: int64

In [7]:
df.isnull().sum(axis=1)

0    0
1    1
2    1
3    1
4    2
5    4
dtype: int64

In [9]:
df.notnull().sum()

a    4
b    5
c    5
d    2
e    5
dtype: int64

In [10]:
df.notnull().sum(axis=1)

0    5
1    4
2    4
3    4
4    3
5    1
dtype: int64

In [11]:
df[df['a'].notnull()]

   a   b   c    d   e
0  0   1   2    1  15
1  3   4   5  NaN  16
2  6   7   8  NaN  17
3  9  10  11  NaN  18

In [12]:
df.dropna()

   a  b  c  d   e
0  0  1  2  1  15

In [14]:
df[['a']].dropna()

   a
0  0
1  3
2  6
3  9

In [15]:
df.fillna(0)

     a     b     c   d     e
0  0.0   1.0   2.0   1  15.0
1  3.0   4.0   5.0   0  16.0
2  6.0   7.0   8.0   0  17.0
3  9.0  10.0  11.0   0  18.0
4  0.0  13.0  14.0   0  19.0
5  0.0   0.0   0.0  10   0.0

In [16]:
df.fillna(method="ffill")

     a     b     c   d     e
0  0.0   1.0   2.0   1  15.0
1  3.0   4.0   5.0   1  16.0
2  6.0   7.0   8.0   1  17.0
3  9.0  10.0  11.0   1  18.0
4  9.0  13.0  14.0   1  19.0
5  9.0  13.0  14.0  10  19.0

In [17]:
df.fillna(method="bfill")

      a     b     c   d     e
0     0     1     2   1    15
1     3     4     5  10    16
2     6     7     8  10    17
3     9    10    11  10    18
4  <NA>    13    14  10    19
5  <NA>  <NA>  <NA>  10  <NA>

In [18]:
df.fillna(method="bfill",axis=1)

      a     b     c     d     e
0   0.0   1.0   2.0   1.0    15
1   3.0   4.0   5.0  16.0    16
2   6.0   7.0   8.0  17.0    17
3   9.0  10.0  11.0  18.0    18
4  13.0  13.0  14.0  19.0    19
5  10.0  10.0  10.0  10.0  <NA>

In [19]:
fill = pd.Series([100, 101, 102])
fill

0    100
1    101
2    102
dtype: int64

In [20]:
df['d'] = df['d'].fillna(fill)
df['d']

0      1.0
1    101.0
2    102.0
3      NaN
4      NaN
5     10.0
Name: d, dtype: float64

In [21]:
df

      a     b     c      d     e
0     0     1     2    1.0    15
1     3     4     5  101.0    16
2     6     7     8  102.0    17
3     9    10    11    NaN    18
4  <NA>    13    14    NaN    19
5  <NA>  <NA>  <NA>   10.0  <NA>

In [22]:
df.fillna(df.median())

     a     b     c      d     e
0  0.0   1.0   2.0    1.0  15.0
1  3.0   4.0   5.0  101.0  16.0
2  6.0   7.0   8.0  102.0  17.0
3  9.0  10.0  11.0   55.5  18.0
4  4.5  13.0  14.0   55.5  19.0
5  4.5   7.0   8.0   10.0  17.0

In [24]:
#Por último, Pandas también puede interporlar los valores faltanes calculando el valor que puede haber existido en el medio.
df_d = pd.concat([df[['d']], df[['d']].interpolate()],axis=1)
df_d.columns = ['d_antes','d_interpolado']
df_d

   d_antes  d_interpolado
0      1.0       1.000000
1    101.0     101.000000
2    102.0     102.000000
3      NaN      71.333333
4      NaN      40.666667
5     10.0      10.000000